project:
  description: REST com Spring Boot 3 e Kotlin
  version: 1.0.0-SNAPSHOT
spring:
  application:
    name: erudio-microservices-kotlin
  boot:
    version: 3.4.0-M1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33069/euridio-microservices-kotlin?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    root: INFO


