version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: db-euridio-microservices-kotlin
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33069:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=euridio-microservices-kotlin
    volumes:
      - db-euridio-microservices-kotlin:/var/lib/mysql
volumes:
  db-euridio-microservices-kotlin: